# Generated by Django 3.2 on 2022-03-15 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_approval',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_created_on']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='booking',
            name='Meal_time',
            field=models.IntegerField(choices=[(0, 'Please choose a booking time'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00'), (9, '18:00')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_comments',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (3, 'Completed')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='dietary_notes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=1, verbose_name='Number of guests'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_tables',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_guest_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Booking_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
