# Generated by Django 3.2 on 2022-03-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20220315_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='primary_guest_id',
            new_name='primary_guest',
        ),
    ]
