# Generated by Django 3.2 on 2022-03-15 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_rename_primary_guest_id_booking_primary_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='primary_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Booking_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
