# Generated by Django 3.2 on 2022-03-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_primary_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
