# Generated by Django 3.2 on 2022-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Meal_time',
            field=models.IntegerField(choices=[(0, 'Please choose:'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00'), (9, '18:00')], default=0),
        ),
    ]
